//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReviewView
    {
        public string Name { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string ReviewerName { get; set; }
        public int Rating { get; set; }
        public string Comments { get; set; }
    }
}
